version: '3.7'

volumes:
    db-data:
        driver: local

services:
    postgres:
        container_name: ${COMPOSE_PROJECT_NAME}_pgsql
        image: postgres
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        volumes:
            - db-data:/var/lib/postgresql/data
        ports:
            - "0.0.0.0:55432:5432"
        restart: unless-stopped

    nginx:
        container_name: ${COMPOSE_PROJECT_NAME}_nginx
        image: nginx:alpine
        links:
            - fpm
        ports:
            - "0.0.0.0:55000:80"
        volumes:
            - "./:/var/www"
            - "./docker-compose/nginx/conf.d:/etc/nginx/conf.d"
            - "./docker-compose/nginx/snippets:/nginx/snippets"

    fpm:
        container_name: ${COMPOSE_PROJECT_NAME}_fpm
        build:
            context: docker-compose/fpm
            args:
                TIMEZONE: ${TIMEZONE}
                DOCKER_USER: ${DOCKER_USER}
        working_dir: /var/www
        volumes:
            - "./:/var/www"
        links:
            - cache

    cache:
        image: redis:5
        container_name: ${COMPOSE_PROJECT_NAME}_cache
        ports:
            - "127.0.0.1:55001:6379"
